### ISSUE TITLE
使用本地模型好像不行，直接报错了

### ISSUE THREAD

**Issue by jlynet** [yangkuowei/ai_exe_cosmic#1]
2025-03-28 15:30:57,775 - langchain_openai_client_v1 - ERROR - 生成过程异常：Expecting value: line 5 column 13 (char 93)
2025-03-28 15:30:57,775 - decorators - WARNING - 第3/3次尝试失败：COSMIC表格生成失败
2025-03-28 15:30:57,775 - decorators - ERROR - 所有3次尝试均失败，最后错误：COSMIC表格生成失败
2025-03-28 15:30:57,775 - __main__ - ERROR - 未处理的异常: COSMIC表格生成失败

单步发现json 解析异常了！
```
  local:
    base_url: "http://localhost:11434/v1"
    model_name: "qwq:latest"
    api_key: "123"
    env_mapping:
      api_key: API_local_KEY
      base_url: API_local_BASE_URL
      model_name: API_local_MODEL
```
